### ISSUE TITLE
Zpětná vazba

### ISSUE THREAD

**Issue by IxAriela** [7r3773n/ukol1#1]
Ahoj, pojala jsi to hodně minimalisticky. Což by nevadilo, ale o to víc bych očekávala splnění všech požadavků a kontrolu, zda vše funguje. Ty ale bohužel nemáš splněny ani základní požadavky a ani sis nezkontrolovala, jak to vypadá na těch github pages, jinak by sis všimla, že ti nefunguje fotka (máš tam adresu na disk v počítači). Takže v první řadě prosím doplň tento základ, poté si to projdu znova a dám konkrétnější zpětnou vazbu na kód.

- [x] přečti si znovu zadání a doplň požadavky z něj
- [x] oprav obrázek
- [x] mezery mají být marginem, ne br
- [x] span je řádkový prvek, většinou se používá pouze na pár slov a moc v sobě nemívá další prvky (občas ano, strong nebo třeba odkaz, prostě další řádkové prvky), na obalení nadpisů, obrázků atd. je určitě vhodnější div. Prosím, oprav i toto.
- [x] v css máš 2x div, spoj je do jednoho, v tomto případě není důvod to mít rozdělené a spíš je to matoucí.

**Comment by 7r3773n** [comment]
Ahoj, dekuji za zpetnou vazbu. Ukol je opraven.

**Comment by IxAriela** [comment]
Ahoj, díky, je to lepší, ale pořád tam jsou dost zásadní základní chyby.

HTML stránka je tvořena hlavičkou (<head>) a tělem (<body>). Tyto jsou vedle sebe a do hlavičky se dávají základní nastavení stránky, které jinak nejsou vidět (to máš správně). V požadavcích je ovšem záhlaví (<header>) a zápatí (<footer>). A záhlaví není to samé jako hlavička, ač chápu, že název může mást. Záhlaví a zápatí se vždy vyskytuje v body (vše, co se má zobrazit na stránce je v body, nikdy mimo něj).

- [ ] dej zápatí do body a přidej i záhlaví
- [ ] stále ti tam chybí odkaz, je úplně jedno jaký, tady je to o tom, zda to umíš. Když ho zkusíš nastylovat do tlačítka, bude to plus :)
- [ ] chybí ti tam uzavření obrázku
- [ ] na prvním řádku css máš "style.css". Css soubory celkem dobře zvládají ignorovat takové zbytečné řádky, ale nepatří to tam a když, tak by to mělo být zakomentované (//). Ale spíš by to tam vůbec nemělo být.


Ještě pár poznámek, které nemusíš opravovat, ale jsou spíš do budoucna :) 

Když nemusíš, nenastavuj výšku. Nikde. Základní je šířka, obecně se s ní lépe pracuje ve vztahu k ostatním prvkům a taky na šířce většinou víc záleží při responsivu.

 Chápu, že jsi tento projekt dělala vizuálem jako wordovský dokument, ale na webu se vertical-align téměř nepoužívá. Myslím, že částečně proto, že už se tolik nezarovnává vertikálně (když se nedělají tabulkové webovky) a taky proto, že máme modernější způsoby, např. flex :) takže spíš jen, že toto je celkem zastaralá technika.

Máš tam jediný div se třídou .box-sizing a na každém nastaveno něco úplně jiného. Je lepší se vyhnout zdvojování stylů (pokud to neděláš s nějakým záměrem samozřejmě) a pokud máš jediný výskyt od každého (a vlastně je to jeden prvek), tak stačí nastylovat jedno z toho.

Při psaní css se hodí mít nějaký systém i v tom, jak jdou prvky za sebou. Při větších projektech se v tom jinak ztratíš :) Nejčastěji se asi používá podle toho, jak to jde v html od vrchu dolů, v tomto případě by tak byl .footer úplně na konci, div a .box-sizing za sebou atd.

**Comment by 7r3773n** [comment]
Ahoj, dekuji za vysvetleni. Ukol jsem opravila, nicmene uvedomuji si, ze jsem ho mohla pojmout jinak a za to se omlouvam.

**Comment by IxAriela** [comment]
Díky za opravy :)

Už mám jen pár připomínek, bez oprav :)

header a footer je v podstatě speciální section, a tudíž by měly být vedle sebe, ne v sobě.

Button se používá spíše u formulářů, pokud máš odkaz jako tlačítko, je lepší nastylovat přímo to `<a>`, většinou stačí display: block, nějaká barva a třeba okraj.

Až si to přečteš, tak to issue můžeš zavřít :)
